config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#dashboard'

  post 'crawl' => 'welcome#start_crawl'
  get 'activity' => 'welcome#activity_feed'
  get 'activity/:id/results' => 'welcome#results', as: "results"

end

app/models/crawl_detail.rb
class CrawlDetail < ActiveRecord::Base
	has_many :product_details
	belongs_to :user
end

app/models/product_detail.rb
class ProductDetail < ActiveRecord::Base
	belongs_to :crawl_details
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :product_details, through: :crawl_details
   has_many :crawl_details
end

app/controllers/application_controller.rb
require 'csv'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_filter :set_current_user

  def set_current_user
    @current_user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def dashboard
  	@activities = current_user.crawl_details.order("crawl_time DESC").limit(9)
  	@total_data_extracted = current_user.product_details.count
  	@total_url_crawled = current_user.crawl_details.count
  end

  def start_crawl
  	puts params[:url]
  	SnapdealScraper.new(current_user, params[:url]).crawl
    respond_to do |format|
      format.js {render js: "window.location.href='"+root_url+"'"}
    end
  end

  def activity_feed
	@activities = current_user.crawl_details
  	respond_to do |format|
      format.html
  	end
  end

  def results
  	@activity = CrawlDetail.find(params[:id])
  	@data = ProductDetail.where("crawl_detail_id=?", @activity.id)
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"product-details\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrawlerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">
  <%= csrf_meta_tags %>

</head>
<body>
  <% if user_signed_in? %>
  <div id="wrapper">
  <div id="navbar" class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsibleMenu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" style="color:white;font-weight:bold;font-size:20px;margin-top:30px">CRAWLER APP</a>
    </div>
    <div class="collapse navbar-collapse" id="collapsibleMenu">
      <ul class="navbar-top-links navbar-nav nav navbar-right">
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-3x"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link" %></li>
        </ul>
         </li>
      </ul>
    </div>
  </div>

    <!-- Sidebar -->

    <nav class="navbar-default navbar-static-side" role="navigation">
      <div class="sidebar-collapse">
        <ul id="side-menu" class="nav">
        <li>
          <div class="user-section">
            <div class="user-section-inner">
                <img src="/assets/user.jpg" alt="">
            </div>
            <div class="user-info">
                <div><%= current_user.email%></div>
                <div class="user-text-online">
                    <span class="user-circle-online btn btn-success btn-circle "></span>&nbsp;Online
                </div>
            </div>
        
          </div>
        </li>

        <li class="selected">
          <a href=<%= root_url %>><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
          <a href=<%= activity_url %>><i class="fa fa-rss-square fa-fw"></i>Activity Feed</a>
        </li>
      </ul>
      </div>
    </nav>
 
    <%= yield %>
 </div>
 <% else %>
   <%= yield %>
  <% end %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/activity_feed.html.erb
<% provide(:title, "Activity Feed") %>

<div id="page-wrapper">
<div class="row">
	<h1 class="page-header">Activity Feed</h1>
	<div class="panel panel-primary">
		<div class="panel-heading">
	  	<i class="fa fa-bar-chart-o fa-fw"></i>Past Activities
		</div>
		<div class="panel-body">
    	<div class="row">
      	<div class="col-lg-12">
      		<div class="table-responsive">
						<table class="table table-bordered table-hover table-striped">
							<thead>
						  	<th>Date</th>
							  <th>Url</th>
							  <th>No of records</th>
							  <th>&nbsp;</th>
							  <th>&nbsp;</th>
							</thead>
							<tbody>
								<% for activity in @activities %>
					  			<tr>
							  		<input type="hidden" value=<%= activity.id%>></input>
							  		<td><%= activity.crawl_time.strftime("%b %e, %Y %H:%M:%S") %></td>
							  		<td><%= activity.crawl_url%></td>
							  		<td><%= activity.no_of_records_crawled %></td>
							  		<td><%=button_to "Crawl again",crawl_url(url: activity.crawl_url), class: "btn btn-default" %></td>
							  		<td><%=link_to "View results", results_url(activity) ,class: "btn btn-default" %></td>
							  	</tr>
					  		<% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/welcome/dashboard.html.erb
<% provide(:title, "Dashboard") %>

<style>
	#crawl_form{
		width:100%;
		display: block;
		text-align: center;
	}
	input[type=text] {
		margin-left: auto;
		margin-right: auto;
		display: inline-block;
		width: 50%;
	}
	input[type=submit] {
		margin-left: auto;
		margin-right: auto;
		display: inline-block;
		width: 30%;
	}

</style>
<div id="page-wrapper">
<div class="row">
	<h1 class="page-header">Dashboard</h1>

	<div class="row">
    <div class="col-lg-offset-2 col-lg-3">
      <div class="alert alert-danger text-center">
        <i class="fa fa-link fa-3x"></i>&nbsp;<b><%= @total_url_crawled%></b> urls crawled
      </div>
    </div>
    <div class="col-lg-offset-2 col-lg-3">
      <div class="alert alert-success text-center">
          <i class="fa  fa-bell fa-3x"></i>&nbsp;<b> <%= @total_data_extracted%></b> data fields extracted 
      </div>
  	</div>
	</div>

	<div class="row">
    <div class="col-lg-6">
      <div class="page-header">
      </div>
	      <div class="jumbotron">
	      	<div class="loading" style="display:none">
	      		<i class="fa-spinner fa fa-spin fa-5x fa-fw"></i>
	      	</div>
          <%= form_tag(crawl_url, remote: true, id: "crawl_form") do %>
          	<div class="form-group">
							<%= text_field_tag :url, "Enter some url...", id: 'url_entry' %>
						</div>
						<%= button_tag "Crawl", class: "crawl-btn btn btn-primary btn-md" %>
					<% end %>
			  </div>
			  <span id="load_msg" style="display:none"><b>Loading...</b></span>
    </div>
		<div class="col-md-6">
			<div class="page-header">
			</div>
		 	<div class="panel panel-primary">
	      <div class="panel-heading">
	        <h3 class="panel-title"><i class="fa fa-rss"></i> Recent Activities</h3>
	      </div>
	      <div class="panel-body feed">
	      	<% for activity in @activities %>
			      <section class="feed-item">
			        <div class="icon pull-left">
			          <i class="fa fa-check"></i>
			        </div>
			        <div class="feed-item-body">
			        	<div class="text">
			        		<a href=<%=results_url(activity.id)%>><%= activity.crawl_url%></a>
			        		<span style="float: right;color: red"><%= activity.crawl_time.to_date %></span>
			        	</div>
			      	</div>
			      </section>
		   		<% end %>
			   	<section class="feed-item">
	    	    <div class="icon pull-left">
		          <i class="fa fa-arrow-down"></i>
		        </div>
		        <div class="feed-item-body">
		          <div class="text">
		            <a href=<%= activity_url %>>Load more...</a>
		          </div>
		        </div>
		   		</section>
	 	    </div>
	 	  </div>
		</div>
	</div>
 </div>
</div>


<script>

$(document).on("click", ".crawl-btn", function(){
 $('#load_msg').show();
});

$(document).ready(function(){
    $(".loading").bind("ajaxSend", function() {
    	debugger
        $(this).show();
    }).bind("ajaxStop", function() {
        $(this).hide();
    }).bind("ajaxError", function() {
        $(this).hide();
    });
 
     });

$(document).on('click', '#url_entry', function(){
	if($(this).val()=="Enter some url..."){
		$(this).val("");
	};
});
	$(document).on('focusout', '#url_entry', function(){
		if($(this).val()==''){
			$(this).val("Enter some url...");
		};
	});
</script>

app/views/welcome/results.csv.erb
<%- headers = ['Title', 'Rating', 'Orig Price', 'Discount Price'] -%>
<%= CSV.generate_line headers %>
<%- @data.each do |product| -%>
<%= CSV.generate_line([product.title, product.rating, product.orig_price, product.discount_price]) -%>
<%- end -%>

app/views/welcome/results.html.erb
<% provide(:title, "Results") %>

<style>
	table th {
		background-color: #3399cc;
	}
	table tr{
		background-color: #99cccc;
	}
</style>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/u/bs-3.3.6/jq-2.2.3,dt-1.10.12,b-1.2.1,b-flash-1.2.1/datatables.min.css"/>

<div id="page-wrapper">
<div class="row">
	<h1 class="page-header">Results</h1>
<div class="panel panel-default">
	<div class="panel-heading">
   <b>Source:</b> <%= @activity.crawl_url %>
   <span style="float:right"><b>Date crawled:</b> <%= @activity.crawl_time.strftime("%b %e, %Y") %></span>
	</div>

	
	<div class="panel-body">
	
	  <div class="table-responsive">
	<div style="margin-top: 20px;margin-left:50px;margin-bottom:0">
		<%=link_to 'Download CSV', results_url(format: :csv), class: 'btn btn-success btn-md' %>
	</div>
			<table id="results-table" class="table table-bordered table-hover">
				<thead>
	  			<th>Product Title</th>
	  			<th>Rating</th>
				  <th>Original Price</th>
				  <th>Discount Price</th>
				  <th>EMI Starts at</th>
				</thead>
				<tbody>
					<% for data in @data %>
				  <tr>
				  	<td><%= data.title %></td>
				  	<td><% data.rating.to_i.times do %><span class="fa fa-star"><%end%><span>
				  		<% if data.rating && data.rating % 1 > 0.5 %>
				  			<span class="fa fa-star-half-empty" 
				  			<% end %>
				  	</td>
				  	<td>Rs. <%= data.orig_price %></td>
				  	<td>Rs. <%=data.discount_price%></td>
				  	<td>Rs. <%=data.emi %></td>
				  </tr>
				  <% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>
</div>

<script>
// Refernce http://jsfiddle.net/8kez8mvy/
$(document).ready(function() {
	jQuery.extend( jQuery.fn.dataTableExt.oSort, {
	"my-currency-pre": function(a) {
     //alert(a.replace(/[^0-9]/gi, ''));
        return parseFloat(a.replace(/[^0-9]/gi, ''));
	},
	"my-currency-asc": function(a,b) {
		return ((a < b) ? -1 : ((a > b) ? 1 : 0));
	},
	"my-currency-desc": function(a,b) {
		return ((a < b) ? 1 : ((a > b) ? -1 : 0));
	}
});

  var table = $('#results-table').DataTable({
  	"dom": 'Bfrtip',
  	"buttons": ['excel', 'pdf', 'csv'],
  	"aoColumnDefs": [
  	{"sType": "my-currency", "aTargets": [2,3,4]}
  	],
  	iDisplayLength: 15
  	
  });
 });
</script>
 <link href="https://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet" />
<!-- <link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet" /> -->
<link href="https://cdn.datatables.net/buttons/1.2.1/css/buttons.dataTables.min.css" rel="stylesheet" />
 <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js"></script>